[package]
name = "uwuid"
description = "Like UUIDs or ULIDs, but better"
version = "0.3.1"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
time = "0.3.11"
